cargo install --git https://github.com/ClementTsang/bottom --locked
cargo install --force --git https://github.com/sxyazi/yazi.git yazi-build
cargo install --no-default-features --git https://github.com/gitui-org/gitui --locked
cargo install --git https://github.com/Rigellute/spotify-tui --locked 
cargo install --git https://github.com/hatoo/oha --locked 
cargo install --git https://github.com/fujiapple852/trippy --locked 
cargo install --git https://github.com/orhun/binsider --locked 
cargo install --git https://github.com/TaKO8Ki/gobang --locked 
cargo install --git https://github.com/Julien-cpsn/ATAC --locked 
cargo install --git https://github.com/bvaisvil/zenith.git --locked 
cargo install --git https://github.com/orhun/kmon --locked 
cargo install --git https://github.com/veeso/termscp --locked
cargo install --git https://github.com/altsem/gitu --locked
cargo install --git https://github.com/shshemi/tabiew --locked
cargo install --git https://github.com/kdheepak/taskwarrior-tui --locked
cargo install --git https://github.com/pythops/oryx --locked
cargo install --git https://github.com/orhun/gpg-tui --locked
cargo install --git https://github.com/tramhao/termusic --locked 
cargo install --git https://github.com/samtay/so --locked 
cargo install --git https://github.com/tarkah/tickrs --locked
cargo install --git https://github.com/orhun/systeroid --locked
cargo install --git https://github.com/Chleba/netscanner --locked
cargo install --git https://github.com/bgreenwell/doxx --locked
cargo install --git https://github.com/itsjunetime/tdf --locked
cargo install --git https://github.com/pythops/impala --locked
cargo install --git https://github.com/pythops/bluetui --locked
cargo install --git https://github.com/zaghaghi/openapi-tui --locked 
cargo install --git https://github.com/meli/meli --locked
cargo install --git https://github.com/josueBarretogit/manga-tui --locked
cargo install --git https://github.com/LucasPickering/slumber --locked 
cargo install --git https://github.com/dustinblackman/oatmeal --locked
cargo install --git https://github.com/sudipghimire533/ytui-music --locked
cargo install --git https://github.com/thomas-mauran/chess-tui --locked
cargo install --git https://github.com/ynqa/sig --locked 
cargo install --git https://github.com/Builditluc/wiki-tui --locked
cargo install --git https://github.com/FedericoBruzzone/tgt --locked
cargo install --git https://github.com/pythops/tenere --locked
cargo install --git https://github.com/Xithrius/twitch-tui --locked
cargo install --git https://github.com/Beastwick18/nyaa --locked
cargo install --git https://github.com/orhun/flawz --locked
cargo install --git https://github.com/ccgauche/ytermusic --locked
cargo install --git https://github.com/Dark-Alex-17/managarr --locked
cargo install --git https://github.com/erikjuhani/basalt --locked
cargo install --git https://github.com/Siriusmart/youtube-tui --locked
cargo install --git https://github.com/dzfrias/projectable --locked
cargo install --git https://github.com/sigoden/proxyfor --locked
cargo install --git https://github.com/dmtrKovalenko/blendr --locked
cargo install --git https://github.com/fioncat/otree --locked
cargo install --git https://github.com/jacek-kurlit/pik --locked
cargo install --git https://github.com/chaosprint/asak --locked
cargo install --git https://github.com/henriklovhaug/md-tui --locked
cargo install --git https://github.com/gin66/tui-logger --locked
cargo install --git https://github.com/jwt-rs/jwt-ui --locked 
cargo install --git https://github.com/vaibhav-mattoo/bitchat-tui --locked 
cargo install --git https://github.com/ckampfe/russ --locked 
cargo install --git https://github.com/13unk0wn/Feather --locked
cargo install --git https://github.com/jansc/ncgopher --locked
cargo install --git https://github.com/sectore/timr-tui --locked 
cargo install --git https://github.com/junkdog/glim --locked
cargo install --git https://github.com/gluesql/glues --locked
cargo install --git https://github.com/linkdd/regname --locked
cargo install --git https://github.com/veeso/tuifeed --locked
cargo install --git https://github.com/AlbanDAVID/Toutui --locked
cargo install --git https://github.com/orhun/tuitar --locked
cargo install --git https://github.com/mach-kernel/launchk --locked
cargo install --git https://github.com/kruseio/hygg --locked
cargo install --git https://github.com/kardwen/passepartui --locked 
cargo install --git https://github.com/Levizor/tray-tui --locked
cargo install --git https://github.com/L4z3x/mal-cli --locked
cargo install --git https://github.com/Canop/safecloset --locked
cargo install --git https://github.com/viseztrance/flow --locked
cargo install --git https://github.com/RohanAdwankar/taskim --locked
cargo install --git https://github.com/Oughie/clock-rs --locked
cargo install --git https://github.com/Chleba/tui-slides --locked 
cargo install --git https://github.com/vaibhav-mattoo/alman --locked
cargo install --git https://github.com/danimelchor/todui --locked 
cargo install --git https://github.com/akinoiro/ssh-list --locked 
cargo install --git https://github.com/codervijo/journalview --locked 
cargo install --git https://github.com/trinhminhtriet/spiko --locked 
cargo install --git https://github.com/drewzemke/tongo --locked 
cargo install --git https://github.com/TheRustyPickle/Rex --locked
cargo install --git https://github.com/vkobinski/CacTui --locked
cargo install --git https://github.com/irishmaestro/fubar --locked
cargo install --git https://github.com/Vaishnav-Sabari-Girish/ComChan --locked 
cargo install --git https://github.com/eyeplum/cicero-tui --locked 
